<a href="https://colab.research.google.com/github/fairyroad/Tensorflow/blob/main/Lab_numpy_in_a_nutshell(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.n_size_ndarray_creation   
->n의 제곱수로 2 dimentional array를 생성하는 ndarray

In [3]:
import numpy as np

In [15]:
def n_size_ndarray_creation(n, dtype=np.int):
  X=np.array(range(n**2)).reshape(n,n)
  return X
#array값 출력  
print(n_size_ndarray_creation(3))
#array가 n*n인지 알아보는것
print(n_size_ndarray_creation(3).shape)
#array의 dimension 알아보는 것
print(n_size_ndarray_creation(3).ndim)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
2


    numpy는 np.array함수를 활용해서 배열을 생성함  
    numpy는 하나의 data type만 배열의 넣을 수 있음
    ->dynamic typing not supported 
    뒤에 나오는 dtype은 data type을 의미하고 numpy는 미리 memory의 크기가 결정되기 때문에 필요함

In [14]:
test_array=np.array([1,4,5,8],float)
print(test_array)
print(test_array[3])
print(test_array.dtype)
print(type(test_array))
print(test_array.shape)
print(test_array.ndim)

[1. 4. 5. 8.]
8.0
float64
<class 'numpy.ndarray'>
(4,)
1


2.zero_or_one_or_empty_ndarray
->shape이 지정된 크기의 ndarray생성하고 행렬의 element는 type에 따라 0,1 또는 empty로 생성됨

In [27]:
def zero_or_one_or_empty_ndarray(shape,type=0,dtype=np.int):
  if type==0:
    return np.zeros(shape=shape,dtype=dtype)
  if type==1:
    return np.ones(shape=shape,dtype=dtype)
  if type==99:
    return np.empty(shape=shape,dtype=dtype)
print(zero_or_one_or_empty_ndarray((2,2),type=0))
print(zero_or_one_or_empty_ndarray((1,4),type=1))
print(zero_or_one_or_empty_ndarray((3,5),type=99))

[[0 0]
 [0 0]]
[[1 1 1 1]]
[[           0 210453397554 206158430253 193273528369 236223201330]
 [210453397588 249108103216 223338299441 227633266746 197568495664]
 [227633266736 227633266745 240518168625 519691042906 433791696995]]


    zeros는 0로 다 채워주는 ndarray생성
    ones는 1로 다 채워주는 ndarray생성
    empty는 shape만 주어지고 비어있는 dnarray인데 memory initialization이 되지 않아서 쓰레기값이 들어갈 수 있음

3.change_shape_of_ndarray   
->입력된 ndarray X를 row의 개수가 n_row인 matrix로 바꿈

In [33]:
def change_shape_of_ndarray(X,n_row):
  if n_row==1:
    return X.flatten()
  return X.reshape(n_row,-1)
X=np.ones((32,32),dtype=np.int)
print(change_shape_of_ndarray(X,1))
print(change_shape_of_ndarray(X,2))

[1 1 1 ... 1 1 1]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


    flatten은 다차원 array를 1차원 array로 바꿔줌

4.concat_ndarray  
->입력된 축을 기준으로 합쳐서 반환함  
->vector인 경우도 처리가능하게!!

In [38]:
def concat_ndarray(X_1,X_2,axis):
  try:
    X=np.array(X_1)
    Y=np.array(X_2)
    return np.concatenate((X,Y),axis=axis)
  except ValueError as e:
    return False

a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
print(concat_ndarray(a,b,0))

a=np.array([1,2])
b=np.array([5,6,7])
print(concat_ndarray(a,b,1))

[[1 2]
 [3 4]
 [5 6]]
False


    예외가 발생하는 코드에서 예외처리를 해주고 싶으면 try: except ValueError as e:를 사용해보기!!
    

4.normalize_ndarray  
->z=(x-x평균)/x의 표준편차로 normalize값으로 변환해서 반환함

In [51]:
def normalize_ndarray(X,axis=99,dtype=np.float32):
  n_row,n_col=X.shape
  if axis==99:
    x_mean=np.mean(X)
    x_std=np.std(X)
    Z=(X-x_mean)/x_std
  if axis==0:
    x_mean=np.mean(X,0).reshape(1,-1)
    x_std=np.std(X,0).reshape(1,-1)
    Z=(X-x_mean)/x_std
  if axis==1:
    x_mean=np.mean(X,1).reshape(n_row,-1)
    x_std=np.std(X,1).reshape(n_row,-1)
    Z=(X-x_mean)/x_std
  return Z
X=np.arange(12,dtype=np.float32).reshape(4,3)
print(normalize_ndarray(X,axis=1))
  


[[-1.2247448  0.         1.2247448]
 [-1.2247448  0.         1.2247448]
 [-1.2247448  0.         1.2247448]
 [-1.2247448  0.         1.2247448]]
