<a href="https://colab.research.google.com/github/fairyroad/Tensorflow/blob/main/Softmax_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.Softmax Classifier

In [2]:
import numpy as np
import tensorflow as tf

numpy는 dynamic typing을 지원하지 않음(다양한 data type이 섞일 수 없음!!)  
dtype은 data type 변환

In [4]:
x_data=[[1,2,1,1],
        [2,1,3,2],
        [3,1,3,4],
        [4,1,5,5],
        [1,7,5,5],
        [1,2,5,6],
        [1,6,6,6],
        [1,7,7,7]]

y_data=[[0,0,1],
       [0,0,1],
       [0,0,1],
       [0,1,0],
       [0,1,0],
       [0,1,0],
       [1,0,0],
       [1,0,0]]

#convert into numpy and float format
#np.array랑 차이점은 data type이 다를때만 copy가능
x_data=np.asarray(x_data,dtype=np.float32)
y_data=np.asarray(y_data,dtype=np.float32)

#num classes
nb_classes=3

In [9]:
#initialize weight and bias

W=tf.Variable(tf.random.normal([4,nb_classes]),name='weight')
b=tf.Variable(tf.random.normal([nb_classes]),name='bias')
variables=[W,b]

#softmax
hypothesis=tf.nn.softmax(tf.matmul(x_data,W)+b)
print(hypothesis)

tf.Tensor(
[[8.5686952e-01 1.2569181e-03 1.4187355e-01]
 [8.3805108e-01 4.0561943e-03 1.5789279e-01]
 [8.7829006e-01 1.1070383e-03 1.2060300e-01]
 [8.6580509e-01 5.0299556e-04 1.3369200e-01]
 [5.6574225e-01 1.6800500e-07 4.3425763e-01]
 [5.1952004e-01 2.9963334e-03 4.7748366e-01]
 [4.6366587e-01 1.3767929e-06 5.3633267e-01]
 [3.7004775e-01 2.1439185e-07 6.2995195e-01]], shape=(8, 3), dtype=float32)


In [ ]:
#cost function
#ylog(y_hat)
cost=tf.reduce_mean(-tf.reduce_sum(y_data*tf.log(hypothesis),axis=1))
optimizer=tf.train.GradientDesceptOptimizer(learning_rate=0.1).minimize(cost)